### ISSUE TITLE
问一个问题V版本的作者是谁一直没找到 V版玩阿尔宙斯时候渐变贴图有问题 反馈问题都找不到地方

### ISSUE THREAD

**Issue by gdf159159** [YidaozhanYa/RyujinxCN#1]
问一个问题V版本的作者是谁一直没找到 V版玩阿尔宙斯时候渐变贴图有问题 反馈问题都找不到地方

**Comment by chiyuki0325** [comment]
就是ryujinx的主作者gdkchan
gdkchan/ryujinx 这个仓库的 vulkan-rel 分支
