### ISSUE TITLE
麻烦关注下你的汉化版本 exe 不显示图标

### ISSUE THREAD

**Issue by shinyoyo** [YidaozhanYa/RyujinxCN#3]
麻烦关注下你的汉化版本 exe 不显示图标。观察了下应该是你编译时候导致的问题？缺少图标和版本信息。麻烦修复下.此外菜单条目上也出现了未翻译的项目了。

**Comment by chiyuki0325** [comment]
- 没有图标的问题是因为 GitHub Actions 的 Windows 编译机是英文版，不支持 GBK 及 UTF-8 编码（Windows 祖传问题）导致只能在 Linux 下编译，而微软的 Linux .NET SDK 又有问题，导致编译出来的 exe 没有图标。
- 我尝试过后续注入图标，但会导致直接原地崩溃，因为 .NET 程序压根就不是标准的 Win32 可执行文件。
- 未翻译的条目欢迎提交 Pull Request。

**Comment by chiyuki0325** [comment]
Windows 就是歌姬!!!!!
