### ISSUE TITLE
一直停在1.1.85了没有继续自动编译了吗？

### ISSUE THREAD

**Issue by kongmao45678** [YidaozhanYa/RyujinxCN#4]
如题

**Comment by chiyuki0325** [comment]
脚本中发布 release 的地方出现了一点问题，可以暂时去[这里](https://nsemuhelper.herokuapp.com/RyujinxCNBuilds/)下载。

release 问题已经修复，可能还需要一点时间试验，所以就再等一等啦！

**Comment by chiyuki0325** [comment]
经验证已修好
